export const usersData = [
  {
    id: "1",
    name: 'John Doe',
    email: 'john@gmail.com',
    imageUrl: 'https://avatars.githubusercontent.com/u/1?v=4',
    age: 25,
    gender: 'Male',
    country: 'Usa',
  },
  {
    id: "2",
    name: 'Ben Smith',
    email: 'ben@gmail.com',
    imageUrl: 'https://avatars.githubusercontent.com/u/2?v=4',
    age: 35,
    gender: 'Male',
    country: 'Great Britan',
  },
  {
    id: "3",
    name: 'Mike Jhonson',
    email: 'mike@gmail.com',
    imageUrl: 'https://avatars.githubusercontent.com/u/3?v=4',
    age: 35,
    gender: 'Male',
    country: 'Australia',
  },
  {
    id: "4",
    name: 'Chris Lee',
    email: 'chris@gmail.com',
    imageUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
    age: 35,
    gender: 'Male',
    country: 'Canada',
  },
];
